### PR TITLE
Added Dark Theme

### PR DESCRIPTION
**Pull request by Thunderbottom**
Hey Paul,

Messaged you on reddit a while ago to make Dark Theme for this application, Had some free time so did it myself.  Feel free to modify as per you wish, but this looks good in the dark. And also, I have written the code similarly to what you did so shouldn't be a problem to remove if it is not required. Here are some screens: 
tev7si4
xrgrja8
hqlx0zc
evb9dut

### CODE REVIEW

**Comment by pflammertsma** [comment]
Thanks so much! I'll make some style changes and merge this very soon.

**Comment by Thunderbottom** [comment]
Hey, I don't know if this was intentional but the dark theme has purple accents now. To be specific, it is purple in the sidebar puzzle selector as well as the alphabet hint bar.

**Comment by Thunderbottom** [comment]
Well to be honest even the splash screen is messed up now

**Comment by pflammertsma** [comment]
Thanks for the feedback. I see purple tinting in the Google Play Games
dialog, which is easy enough to change, but the sidebar and hint bar are
blue for me. I'll take a look at where color resources are used.

**Pull request merged**
